# -*- coding: utf-8 -*-
"""Movie_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LqczDWQSd_xNAYxxLEBF03U5f8XqzlB
"""

!pip install pandas scikit-learn -q

!ls

from recommender import MovieRecommender

engine = MovieRecommender("movies.csv")
print(f"Loaded {len(engine.df)} movies")

results, matched_title = engine.recommend("The Dark Knight", top_n=5)

print(f"Because you watched: {matched_title}\n")
for i, r in enumerate(results, 1):
    print(f"{i}. {r['title']:<30} {r['genres']:<30} similarity={r['similarity']}")

import pandas as pd
pd.DataFrame(results)

for title in ["Inception", "Parasite", "Toy Story"]:
    results, matched = engine.recommend(title, top_n=3)
    print(f"\n{matched} →", [r['title'] for r in results])

